version: '3'

services: 
    node_js_app: 
        image: nodejs_api:v2
        env_file:
            - ./.env
        build:
            context: "./node_js_app"
            dockerfile: "Dockerfile"
            # image: "node:10"
            # volumes:
            #     - ./induction_ms:/var/www/
            # command:  ["npm", "run", "start:dev"]
        ports:
            - '8001:4001'
            - "9229:9229"
        restart: on-failure
        deploy:
            replicas: 3

# version: '2.1'

# services:
#   test_nodejs_server:
#     image: test_nodejs_server
#     build: .
#     environment:
#       NODE_ENV: production
#     ports:
#       - 3001:3001





# FROM node:10.13-alpine
# ENV NODE_ENV production
# WORKDIR /usr/src/app
# COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
# RUN npm install --production --silent && mv node_modules ../
# COPY . .
# EXPOSE 3001
# CMD npm start